blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from .views import (BlogPostListView,
                    BlogPostDetailView,
                    BlogPostCreateView,
                    BlogPostUpdateView,
                    BlogPostDeleteView,
                    ContactView,
                    )

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogPostListView.as_view(), name='blog_list'),
    path('blog/create/', BlogPostCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogPostUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/', BlogPostDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blog_delete'),
    path('contacts/', ContactView.as_view(), name='blog_contact'), ]

catalog/urls.py
from django.urls import path
from .views import HomePageView, ContactsPageView, ProductListView, ProductDetailView, ProductCreateView, \
    ProductDeleteView, ProductUpdateView

app_name = 'catalog'

urlpatterns = [
    path('home/', HomePageView.as_view(), name='home'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
]

config/urls.py
from xml.etree.ElementInclude import include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from tempfile import template

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

app_name = 'users'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:home'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

catalog/models.py
from django.db import models
from django import forms


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(verbose_name='описание категории', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='название продукта')
    description = models.TextField(verbose_name='описание продукта', blank=True, null=True)
    image = models.ImageField(upload_to='media/photos', verbose_name='изображение', blank=True, null=True)
    price = models.IntegerField(verbose_name='цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name', 'price', 'created_at', 'category']

catalog/forms.py
from django.forms import ModelForm
from .models import Category, Product
from django.core.exceptions import ValidationError
from django.forms.fields import BooleanField


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        banned_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]
        name = self.cleaned_data.get('name')
        for banned_word in banned_words:
            if banned_word in name.lower():
                raise ValidationError(f'Слово "{banned_word}" недопустимо в имени товара')
        return name

    def clean_description(self):
        banned_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]
        description = self.cleaned_data.get('description')
        for banned_word in banned_words:
            if banned_word in description.lower():
                raise ValidationError(f'Слово "{banned_word}" недопустимо в описании товара')
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise ValidationError(f'Цена не должна быть отрицательной')
        return price

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            if image.size > 5 * 1024 * 1024:
                raise ValidationError('Размер файла не должен превышать 5 МБ')
            if not (image.name.lower().endswith('.jpg') or image.name.lower().endswith('.png')):
                raise ValidationError('Вы можете загрузить только .JPG и .PNG файлы')

catalog/views.py
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView, UpdateView, DeleteView, CreateView
from .models import Product
from django.urls import reverse
from .forms import ProductForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin



class HomePageView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    context_object_name = 'products'


class ContactsPageView(TemplateView):
    template_name = 'catalog/contacts.html'


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'


class ProductUpdateView(LoginRequiredMixin,UpdateView):
    model = Product
    template_name = 'catalog/product_form.html'
    fields = ['name', 'description', 'image', 'price']
    success_url = reverse_lazy('catalog:product_list')


class ProductCreateView(LoginRequiredMixin,CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:product_list')


# FBV
#
# def home_page(request):
#     products = Product.objects.all()
#     context = {'products': products}
#     return render(request, 'catalog/home.html', context)
#
# def contacts_page(request):
#      return render(request, 'catalog/contacts.html')
#
#
#
# def product_list(request):
#     products = Product.objects.all()
#     context = {
#         'products': products
#     }
#     return render(request, 'catalog/product_list.html', context)
#
#
# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {'product': product}
#     return render(request, 'catalog/product_detail.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/catalog/home/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/catalog/contacts/">Контакты</a>
        <!-- Кнопки входа и регистрации -->
        {% if user.is_authenticated %}
	                    <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
	                        {% csrf_token %}
	                        <button type="submit" class="p-2 btn btn-outline-primary">Выйти
	                        </button>
	                    </form>
                {% else %}
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
</div>
{% block content %}
{% endblock %}

<style>
    body {
        font-family: Arial, sans-serif;
        display: flex;
        flex-direction: column;
        align-items: stretch;
        padding: 20px;
        background-color: #f4f4f4;
    }
    .card img {
        width: 100%;
        height: auto;
    }
</style>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href=" catalog/contacts ">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html'%}
{% block content %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        </ul>
</div>
</div>
</footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalog</title>
    <style>
        h1 {
            margin-bottom: 20px;
        }
        .product-list {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            max-width: 1200px;
        }
        .card {
            background-color: white;
            border-radius: 8px;
            width: 200px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s;
            overflow: hidden;
            text-align: center;
        }
        .card:hover {
            transform: scale(1.05);
        }
        .card h2 {
            font-size: 20px;
            margin: 10px 0;
        }
        .card p {
            margin: 5px 0;
            color: #555;
        }
    </style>
</head>
<body>
<h1>Каталог товаров</h1>
<a href="{% url 'catalog:product_create' %}" class="btn btn-primary"> Создать новый продукт </a>
<div class="product-list">
    {% for product in products %}
    <div class="card">
        <img src="{{ product.image | media_filter }}" alt="{{ product.name }}">
        <h2>{{ product.name }}</h2>
        <p>Цена: {{ product.price }}</p>
        <p>{{ product.description | truncatechars:100 }}</p>
        <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Посмотреть</a>
    </div>

    {% empty %}
    <p>Нет доступных товаров.</p>
    {% endfor %}
</div>
</body>
</html>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="coll-4">
            <form class="row" method="post" enctype="multipart/from-data">
                <div class="card">
                    <p class="card-text">Подтвердить удаление: {{ object.title }}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h1>Информация о продукте</h1>
                        <p class="card-text">Название продукта: {{ product.name }}</p>
                        <p class="card-text">Описание продукта: {{ product.description | truncatechars:100}} </p>
                        <p class="card-text">Изображение: <img src="{{ product.image | media_filter }}" width=" 400"
                                                               height=" 270"></p>
                        <p class="card-text">Категория продукта: {{ product.category}} </p>
                        <p class="card-text">Стоимость: {{ product.price }}</p>
                        <p class="card-text">Дата создания: {{ product.created_at |date:"d M Y"}}</p>
                        <p class="card-text">Дата последнего изменения: {{ product.updated_at |date:"d M Y"}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Вернуться</a>
                                <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-secondary">Редактировать</a>
                                <a href="{% url 'catalog:product_delete' object.pk %}"
                                   class="btn btn-danger ">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}


{% block title %}Добавить продукт{% endblock %}

{% block content %}


<div class="container">
    <div class="row text-start">
        <h1 class="mb-4">Добавить продукт</h1>
        <div class="col-12">
            <div class="card mb-4 box-shadow">

                <div class="card-body">

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                        {% else %}
                        <button type="submit" class="btn btn-outline-primary">Добавить</button>
                        {% endif %}
                         <a href="{% url 'catalog:product_list' %}" calss="btn ntn-primary"> Отменить </a>
                    </form>


                </div>
            </div>
        </div>


    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}
<head>
    <h1>Список товаров</h1>
</head>
<body>
<a href="{% url 'catalog:product_create' %}" class="btn btn-primary"> Создать новый продукт </a>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.image | media_filter }}" width=" 400" height=" 270">
                    <div class="card-body">
                        <p class="card-text">Название: {{ product.name | upper }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}"
                                   role="button">Посмотреть</a>
                                <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-secondary">Редактировать</a>
                                <a href="{% url 'catalog:product_delete' product.pk %}"
                                   class="btn btn-danger ">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</body>
{% endblock %}